# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lKJZsm9JoLQjk5M2hEuhXgjfZOPV4PNR
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
y = np.sin(x)

plt.plot(x, y)
plt.title('Sinus Funktsiyasi Grafiki')
plt.xlabel('X qiymatlari')
plt.ylabel('Sin(X)')
plt.show()

x = np.random.rand(50)
y = np.random.rand(50)

plt.scatter(x, y, color='blue')
plt.title('Tasodifiy Nuqtalar Scatter Grafiki')
plt.xlabel('X qiymatlari')
plt.ylabel('Y qiymatlari')
plt.show()

!pip install opencv-python matplotlib

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("rasm3.jpg")
cv2_imshow(rasm)

oqqora= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("rasm2.jpg")
cv2_imshow(rasm)

oqqora= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("rasm1.jpg")
cv2_imshow(rasm)

oqqora= cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

import pandas as pd
df = pd.read_csv('kasallar soni.csv')
print(df)

filtered_df = df[df['Country'] == 'Afghanistan']
print(len(filtered_df))

filtered_df = df[df['Continent'] == 'South America']
print(len(filtered_df))